Rewritten into java
wouterbulten/kalmanjs pull request #7
Opened 2017-07-26 05:51 UTC by ysf199711

Rewritten the filter into java for java application

2017-07-26 19:01 UTC, wouterbulten requested changes
Hi @ysf199711! Thank you for your pull request. This repo was originally only for the Javascript version of the 1D kalman filter (hence the JS in the name).

However, I get a lot of questions regarding a Java implementation so there is merit in this translation. I would like, however, to keep the main repo/dir clean of any non-js files. Instead, I would like to add a `contrib` folder with contributions.

So, could you move this file to: /contrib/java/KalmanFilter.java? I also added some comments to your code.

After the changes I will merge the branch. Again, thanks for your contributions!

2017-07-26 19:01 UTC, wouterbulten commented on src/KalmanFilter.java
> + *
Can you add the license of the project here? See for example the docblock on the js file.

2017-07-26 19:01 UTC, wouterbulten commented on src/KalmanFilter.java
> +package sye8.utils;
Could you rename this package?

2017-07-26 19:01 UTC, wouterbulten commented on src/KalmanFilter.java
> +	public void setMeasurementNoise(double noise){
Please add the docblock here

2017-07-26 19:01 UTC, wouterbulten commented on src/KalmanFilter.java
> +	public void setProcessNoise(double noise){
Please add the docblock here

2017-07-27 01:35 UTC, ysf199711 commented
Location and comments updated. Package name will be left as (default) as new package name is undecided. Added LGPL v3 license

2017-07-28 10:00 UTC, wouterbulten commented
Thanks for the changes! I will merge it in the next few days

2017-07-28 10:00 UTC, wouterbulten approved these changes

2017-07-30 14:50 UTC, merged